"""Kernel de contratos (ARCHITECTURE.md §19). Mudanças aqui exigem PR dedicado."""

from app.core.schemas.agent import (
    AgentCard,
    AgentResult,
    Assumption,
    LLMUsage,
    ReworkInstruction,
    TaskSpec,
    ToolCallSpec,
)
from app.core.schemas.case import (
    AgentCardState,
    AgentStatus,
    CaseCounters,
    CaseState,
    CaseStatus,
    CreateCaseRequest,
    DemoOptions,
    HumanReviewRequest,
    InputRequest,
    MissingInfoRequest,
)
from app.core.schemas.context import CaseScope, ExecutionContext, UserIdentity
from app.core.schemas.events import (
    AUDIT_EVENT_TYPES,
    Event,
    EventType,
    LLMEventPayload,
    SecurityEventKind,
    ToolEventPayload,
)
from app.core.schemas.evidence import (
    AgentOutputRecord,
    CalculationRecord,
    EvidenceBundle,
    EvidenceItem,
    EvidenceRef,
    SourceRecord,
)
from app.core.schemas.outputs import (
    OUTPUT_SCHEMAS,
    AIReviewOutput,
    Alternative,
    EligibilityOutput,
    EvidencedItem,
    Finding,
    InterpretedDemand,
    MetricsSummary,
    MissingItem,
    ReviewOutput,
    RiskLLMOutput,
    RiskOutput,
    ScenarioResult,
    StructuringOutput,
)
from app.core.schemas.report import Report
from app.core.schemas.tools import Decision, ToolResult, ToolSpec

__all__ = [
    "AUDIT_EVENT_TYPES",
    "OUTPUT_SCHEMAS",
    "AIReviewOutput",
    "AgentCard",
    "AgentCardState",
    "AgentOutputRecord",
    "AgentResult",
    "AgentStatus",
    "Alternative",
    "Assumption",
    "CalculationRecord",
    "CaseCounters",
    "CaseScope",
    "CaseState",
    "CaseStatus",
    "CreateCaseRequest",
    "Decision",
    "DemoOptions",
    "EligibilityOutput",
    "Event",
    "EventType",
    "EvidenceBundle",
    "EvidenceItem",
    "EvidenceRef",
    "EvidencedItem",
    "ExecutionContext",
    "Finding",
    "HumanReviewRequest",
    "InputRequest",
    "InterpretedDemand",
    "LLMEventPayload",
    "LLMUsage",
    "MetricsSummary",
    "MissingInfoRequest",
    "MissingItem",
    "Report",
    "ReviewOutput",
    "ReworkInstruction",
    "RiskLLMOutput",
    "RiskOutput",
    "ScenarioResult",
    "SecurityEventKind",
    "SourceRecord",
    "StructuringOutput",
    "TaskSpec",
    "ToolCallSpec",
    "ToolEventPayload",
    "ToolResult",
    "ToolSpec",
    "UserIdentity",
]
